### ISSUE TITLE
PyVista is not properly rendering in Docker containers

### ISSUE THREAD

**Issue by daniellivingston** [lanl/tinerator#9]
Known issue: https://github.com/pyvista/pyvista/issues/1559, https://github.com/pyvista/pyvista/issues/1309

Related: https://github.com/pyvista/pyvista/issues/1281, https://github.com/pyvista/pyvista/issues/1256

**Comment by daniellivingston** [comment]
Fixed in 64a1c7e6cb508623cd6cd1d50e44e5b26f2606b6

**Comment by pinshuai** [comment]
Hi Daniel,

I still see this rendering issue in the latest docker container. 

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_44/2650344654.py in <module>
----> 1 dem_50cm.plot()

~/tinerator/tinerator/gis/raster.py in plot(self, layers, mapbox_style, show_legend, raster_cmap, zoom_scale, write_image, write_html, **kwargs)
    362             objects += layers
    363 
--> 364         plot2d(
    365             objects,
    366             mapbox_style=mapbox_style,

~/tinerator/tinerator/visualize/__init__.py in plot2d(objects, mapbox_style, show_legend, raster_cmap, zoom_scale, write_image, write_html, **kwargs)
    125     with warnings.catch_warnings():
    126         warnings.simplefilter("ignore")
--> 127         run_server(layout, **kwargs)
    128 
    129 

~/tinerator/tinerator/visualize/config.py in run_server(layout, mode, **kwargs)
    147         run_server_default(layout, **kwargs)
    148     elif mode == ServerTypes.JUPYTER:
--> 149         run_server_jupyter(layout, **kwargs)
    150     elif mode == ServerTypes.WINDOWED:
    151         run_server_windowed(layout, **kwargs)

~/tinerator/tinerator/visualize/config.py in run_server_jupyter(layout, **kwargs)
    126     app.layout = layout
    127     app.run_server(mode="inline", **kwargs)
--> 128     print(app.status())
    129 
    130 

AttributeError: 'JupyterDash' object has no attribute 'status'
```

The interactive plot is not shown. It says "127.0.0.1 refused to connect." 

Have you pushed the fix to Docker container?

-Pin
